export const useBoardState = () =>
  useState("board", () => [
    [
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
    ],
    [
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
    ],
    [
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
      [0, false],
      [1, false],
    ],
    [
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
    ],
    [
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
      [0, false],
    ],
    [
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
    ],
    [
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
    ],
    [
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
      [2, false],
      [0, false],
    ],
  ]);
